' Gambas module file

Export

Public Function CommandInPath(sCommand As String) As Boolean

  Dim sResult As String

  Shell "which " & sCommand To sResult

  Return sResult

End

Public Function CharacterSets() As String[]

  Dim sIconvList As String
  Dim aCharacterSets As String[]

  Shell "iconv --list" To sIconvList
  sIconvList = Replace$(sIconvList, "//", "")
  aCharacterSets = Split(sIconvList, "\n")
  aCharacterSets.Remove(aCharacterSets.Max, 1)

  Return aCharacterSets

End

Public Function MimeEncoding(sFilePath As String) As String

  Dim sResult As String

  Shell "file --brief --mime-encoding " & sFilePath To sResult
  sResult = Trim(Upper(sResult))

  Return sResult

End

Public Function MimeType(sFilePath As String) As String

  Dim sResult As String

  Shell "file --brief --mime-type " & sFilePath To sResult
  sResult = Trim(sResult)

  Return sResult

End
